- id: '1777369857770'
  alias: Synchroniser l'état du rad simulator
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - climate.poele_pellets_fake
  - trigger: state
    entity_id:
    - switch.rad_simulator_heater_switch_pwm
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: climate.poele_pellets_fake
      state:
      - heat
    then:
    - action: switch.turn_on
      metadata: {}
      target:
        entity_id: switch.rad_simulator_heater_switch_pwm
      data: {}
    - action: persistent_notification.create
      metadata: {}
      data:
        message: Rad vient d'être allumé
        title: Etat du radiateur simulateur
      enabled: false
    else:
    - action: switch.turn_off
      metadata: {}
      target:
        entity_id: switch.rad_simulator_heater_switch_pwm
      data: {}
    - action: persistent_notification.create
      metadata: {}
      data:
        message: Rad vient d'être éteint
        title: Etat du radiateur simulateur
      enabled: false
  mode: single
